### ISSUE TITLE
"File not found" exception on windows when hot reload processing

### ISSUE THREAD

**Issue by SkReD** [hoplon/hoplon#133]
After first or second change to code, which cause a hot reload and rebuild, the following error ocures

```
Exception in thread "Thread-17" java.io.FileNotFoundException: src\game\pages\index.cljs.hl___jb_tmp___ (Не удается найти указанный файл)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at clojure.java.io$fn__9235.invoke(io.clj:344)
        at clojure.lang.MultiFn.invoke(MultiFn.java:238)
        at clojure.java.io$copy.doInvoke(io.clj:396)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.core$partial$fn__4527.invoke(core.clj:2493)
        at boot.file$copy_with_lastmod.invoke(file.clj:163)
        at boot.file$sync_BANG_.doInvoke(file.clj:223)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:634)
        at boot.core$sync_user_dirs_BANG_$fn__505.invoke(core.clj:123)
        at boot.core$sync_user_dirs_BANG_.invoke(core.clj:120)
        at boot.core$set_user_dirs_BANG_$on_change__526.invoke(core.clj:160)
        at boot.core$watch_dirs$fn__733.invoke(core.clj:546)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)

```

And this exception occures after every save file which is watched

```
java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: target\index.html.out\hoplon\app_pages\_index_DOT_html.js
    java.nio.file.AccessDeniedException: target\index.html.out\hoplon\app_pages\_index_DOT_html.js
    file: "target\\index.html.out\\hoplon\\app_pages\\_index_DOT_html.js"
sun.nio.fs.WindowsException.translateToIOException           WindowsException.java:   83
  sun.nio.fs.WindowsException.rethrowAsIOException           WindowsException.java:   97
  sun.nio.fs.WindowsException.rethrowAsIOException           WindowsException.java:  102
                   sun.nio.fs.WindowsFileCopy.copy            WindowsFileCopy.java:  165
         sun.nio.fs.WindowsFileSystemProvider.copy  WindowsFileSystemProvider.java:  278
                                               ...
                             boot.filesystem/copy!                  filesystem.clj:   51
                            boot.filesystem/patch!                  filesystem.clj:   82
                                               ...
         boot.core/fileset-syncer/fn/iter/fn/fn/fn                        core.clj:  776
               clojure.core/binding-conveyor-fn/fn                        core.clj: 1916
                                               ...

```

OS: Windows 7 x64

Java: 1.8.0_73

Boot -V output:

```
#http://boot-clj.com
#Tue May 17 22:30:01 MSK 2016
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.2
```

**Comment by laforge49** [comment]
I'll note that things tend to work better on Windows 10. Do you have access to a windows 10 machine to test on? Or linux?

**Comment by SkReD** [comment]
Yes, i think i could try on windows 10 and ubuntu. Maybe windows 8.1 too

**Comment by SkReD** [comment]
So here is my results. 
First i update all my dependecnies to latest versions. Also update clojure to 1.8.0 and boot to 2.6.0-SNAPSHOT. Then i try on windows 7 again and it continuos to fail, also fails happen on windows 8.1.
I also try set `BOOT_EMIT_TARGET=no` and `useFileMappedBuffe`r to `false ` and its not help on those OS.
On windows 10 everything works without errors and without any fixes except latest version of dependecies.
What i notice is that fail happen only after first time when "index.html" page loaded. Even when `reload` task not used

**Comment by flyboarder** [comment]
I'm going to close this as it seems mostly related to Boot on Windows. Generally for development we recommend Windows 10 or *nix based OS. There is also a note on the Boot README under Windows, that previous versions of Windows have known issues.
